DROP TABLE ADOPTCOMMENT;
DROP SEQUENCE ACOMNO;


CREATE TABLE ADOPTCOMMENT(

    ACOMNO NUMBER NOT NULL PRIMARY KEY,
    ANO NUMBER NOT NULL,
    WRITER VARCHAR2(200),
    ACOMCONTENT VARCHAR2(2000),
    ACOMDATE DATE NOT NULL,
    
    FOREIGN KEY(ANO) REFERENCES ADOPT(ANO) 



);


SELECT * FROM ADOPT;
INSERT INTO ADOPTCOMMENT VALUES(ACOMNO.NEXTVAL, 12, '관리자','더미댓글입니다.',SYSDATE);

SELECT * FROM ADOPTCOMMENT
WHERE ano = 12;


COMMIT
