DROP TABLE ADOPTCOMMENT;
DROP SEQUENCE ACOMNO;

CREATE SEQUENCE ACOMNO;
CREATE TABLE ADOPTCOMMENT(

    ACOMNO NUMBER PRIMARY KEY,
    ANO NUMBER NOT NULL,
    WRITER VARCHAR2(200) NOT NULL,
    ACOMCONTENT VARCHAR2(2000) NOT NULL,
    ACOMDATE DATE NOT NULL,
    
    FOREIGN KEY(ANO) REFERENCES ADOPT(ANO) 


);


SELECT * FROM ADOPT;
INSERT INTO ADOPTCOMMENT VALUES(ACOMNO.NEXTVAL, 1, '관리자','더미댓글입니다.',SYSDATE);

SELECT * FROM ADOPTCOMMENT




ALTER TABLE ADOPTCOMMENT ADD COLUMN ACOM_CNT INT DEFAULT 0;


COMMIT



