-- 채팅 기능 관련 테이블

DROP SEQUENCE MSGNO;
DROP TABLE MESSAGE;

DROP SEQUENCE CHATROOMNO;
DROP TABLE CHATROOM;

CREATE SEQUENCE MSGNO;
CREATE TABLE MESSAGE(
    MSGNO NUMBER NOT NULL PRIMARY KEY,
    MSGSENDERNO NUMBER NOT NULL,
    MSGRECEIVERNO NUMBER NOT NULL,
    MSGCONTENT VARCHAR2(2000) NOT NULL,
    MSGSENDTIME DATE NOT NULL,
    CHATROOMNO NUMBER NOT NULL,
    CHATREQUESTERNO NUMBER NOT NULL,
    CHATRESPONSORNO NUMBER NOT NULL,
    SENDERMNICK VARCHAR2(2000) NOT NULL,
    MSGSENDTIMESCRIPT VARCHAR2(2000) NOT NULL,

    FOREIGN KEY(CHATREQUESTERNO) REFERENCES MEMBER(MNO)ON DELETE CASCADE, 
    FOREIGN KEY(CHATRESPONSORNO) REFERENCES MEMBER(MNO)ON DELETE CASCADE
    );

CREATE SEQUENCE CHATROOMNO;
CREATE TABLE CHATROOM(
    CHATROOMNO NUMBER NOT NULL PRIMARY KEY,
    CHATREQUESTERNO NUMBER NOT NULL,
    CHATRESPONSORNO NUMBER NOT NULL,
    CHATREQUESTERMNICK VARCHAR2(1000)NOT NULL,
    CHATRESPONSORMNICK VARCHAR2(1000)NOT NULL,

    FOREIGN KEY(CHATREQUESTERNO) REFERENCES MEMBER(MNO)ON DELETE CASCADE, 
    FOREIGN KEY(CHATRESPONSORNO) REFERENCES MEMBER(MNO)ON DELETE CASCADE
);

SELECT * 
FROM CHATROOM;

SELECT * 
FROM MESSAGE;

COMMIT

-- 알림 기능 관련 (1:1 채팅 알림)
DROP SEQUENCE NOTICENOSEQ;
DROP TABLE NOTICE;

CREATE SEQUENCE NOTICENOSEQ;
CREATE TABLE NOTICE(
    NOTICENO NUMBER NOT NULL PRIMARY KEY,
    NOTICESENDERNO NUMBER NOT NULL,
    NOTICERECEIVERNO NUMBER NOT NULL,
    NOTICECONTENT VARCHAR2(2000) NOT NULL,
    NOTICETIME DATE NOT NULL,
    NOTICETIMESCRIPT VARCHAR2(2000) NOT NULL, 

    FOREIGN KEY(NOTICESENDERNO) REFERENCES MEMBER(MNO)ON DELETE CASCADE, 
    FOREIGN KEY(NOTICERECEIVERNO) REFERENCES MEMBER(MNO)ON DELETE CASCADE
);


COMMIT
