-- 채팅 기능 관련

DROP TABLE CHATROOM;
DROP TABLE MESSAGE;

DROP SEQUENCE MSGNO;
DROP SEQUENCE CHATROOMID;

CREATE SEQUENCE MSGNO;
CREATE TABLE MESSAGE(
    MSGNO NUMBER NOT NULL PRIMARY KEY,
    MSGSENDERNO NUMBER NOT NULL,
    MSGRECEIVERNO NUMBER NOT NULL,
    MSGCONTENT VARCHAR2(2000) NOT NULL,
    MSGSENDTIME DATE NOT NULL,
    CHATROOMNO NUMBER NOT NULL,
    CHATREQUESTERNO NUMBER NOT NULL,
    CHATRESPONSORNO NUMBER NOT NULL,
    SENDERMNICK VARCHAR2(2000) NOT NULL,
    MSGSENDTIMESCRIPT VARCHAR2(2000) NOT NULL,

    FOREIGN KEY(CHATREQUESTERNO) REFERENCES MEMBER(MNO)ON DELETE CASCADE, 
    FOREIGN KEY(CHATRESPONSORNO) REFERENCES MEMBER(MNO)ON DELETE CASCADE
    );

CREATE SEQUENCE CHATROOMNO;
CREATE TABLE CHATROOM(
    CHATROOMNO NUMBER NOT NULL PRIMARY KEY,
    CHATREQUESTERNO NUMBER NOT NULL,
    CHATRESPONSORNO NUMBER NOT NULL,
    CHATREQUESTERMNICK VARCHAR2(1000)NOT NULL,
    CHATRESPONSORMNICK VARCHAR2(1000)NOT NULL,

    FOREIGN KEY(CHATREQUESTERNO) REFERENCES MEMBER(MNO)ON DELETE CASCADE, 
    FOREIGN KEY(CHATRESPONSORNO) REFERENCES MEMBER(MNO)ON DELETE CASCADE
);

INSERT INTO CHATROOM
VALUES(CHATROOMNO.NEXTVAL, 2, 1, '이순신', '관리자');
INSERT INTO CHATROOM
VALUES(CHATROOMNO.NEXTVAL, 3, 1, '홍길동', '관리자');


select * 
from CHATROOM ;

SELECT * 
FROM MESSAGE;

commit

SELECT * 
		FROM CHATROOM 
		WHERE ( CHATREQUESTERNO = 2 and CHATRESPONSORNO = 1 )
				OR 
			  ( CHATREQUESTERNO = 1 and CHATRESPONSORNO = 2 );



