-- 입양일기 테이블
DROP TABLE DIARY;
DROP SEQUENCE DNOSEQ;

CREATE SEQUENCE DNOSEQ;
CREATE TABLE DIARY(
    DNO NUMBER PRIMARY KEY, 
    MNO NUMBER NOT NULL, 
    DCONTENT VARCHAR2(2000) NOT NULL,
    DDATE DATE NOT NULL, 

    CONSTRAINT FK_MNO_DIARY FOREIGN KEY(MNO) REFERENCES MEMBER(MNO)
);

INSERT INTO DIARY
VALUES(DNOSEQ.NEXTVAL, 1, '첫번째 입양일기 글 내용입니다', SYSDATE);
INSERT INTO DIARY
VALUES(DNOSEQ.NEXTVAL, 2, '두번째 입양일기 글 내용입니다', SYSDATE);

SELECT * 
FROM DIARY;


-- 좋아요 테이블
DROP TABLE LIKETABLE;
DROP SEQUENCE LIKENOSEQ;

CREATE SEQUENCE LIKENOSEQ;
CREATE TABLE LIKETABLE(
    LIKENO NUMBER PRIMARY KEY, 
    DNO NUMBER NOT NULL, 
    MNO NUMBER NOT NULL, 
    LIKEYN VARCHAR2(10) NOT NULL, 

    CONSTRAINT FK_MNO_LIKE FOREIGN KEY(MNO) REFERENCES MEMBER(MNO), 
    CONSTRAINT FK_DNO_LIKE FOREIGN KEY(DNO) REFERENCES DIARY(DNO)
);

INSERT INTO LIKETABLE
VALUES(LIKENOSEQ.NEXTVAL, 1, 2, 'Y');

SELECT *
FROM LIKETABLE;
INSERT INTO MEMBER VALUES(
MNO.NEXTVAL,1,'Y','user1','1234','11111','경기도 구리시','**아파트','이순신','거북선대왕','010-1234-1234'
);