-- 입양일기 테이블
DROP TABLE DIARY CASCADE CONSTRAINTS;
DROP SEQUENCE DNOSEQ;

CREATE SEQUENCE DNOSEQ;
CREATE TABLE DIARY(
    DNO NUMBER PRIMARY KEY, 
    MNO NUMBER NOT NULL, 
    DCONTENT VARCHAR2(2000) NOT NULL,
    DDATE DATE NOT NULL, 
    DIARYIMG VARCHAR2(2000) NOT NULL, 
    DIARYTHUMBIMG VARCHAR2(2000) NOT NULL,

    CONSTRAINT FK_MNO_DIARY FOREIGN KEY(MNO) REFERENCES MEMBER(MNO)
);

INSERT INTO DIARY
VALUES(DNOSEQ.NEXTVAL, 1, '첫번째 입양일기 글 내용입니다', SYSDATE, 'aaa.jpg', 'aaa.jpg');
INSERT INTO DIARY
VALUES(DNOSEQ.NEXTVAL, 1, '두번째 입양일기 글 내용입니다', SYSDATE, 'aaa.jpg', 'aaa.jpg');
INSERT INTO DIARY
VALUES(DNOSEQ.NEXTVAL, 2, '이순신의 입양일기 글 내용입니다~~', SYSDATE, 'aaa.jpg', 'aaa.jpg');

INSERT INTO DIARY
VALUES(DNOSEQ.NEXTVAL, 2, '무한스크롤 테스트용 입양일기 글', SYSDATE, 'aaa.jpg', 'aaa.jpg');

SELECT * 
FROM DIARY;

commit


INSERT INTO DIARYREPLY VALUES(
DRNOSEQ.NEXTVAL, 14, DRGROUPNOSEQ.NEXTVAL, 0, 0, 2, '첫 번째 댓글', SYSDATE
);

INSERT INTO DIARYREPLY VALUES(
DRNOSEQ.NEXTVAL, 14, DRGROUPNOSEQ.NEXTVAL, 0, 0, 1, '두 번째 댓글', SYSDATE
);

SELECT * FROM DIARYREPLY

INSERT INTO DIARYREPLY VALUES(
DRNOSEQ.NEXTVAL, 14, 21, 1, 1, 2, '두 번째 글 첫 번째 댓글의 답글', SYSDATE
)

INSERT INTO DIARYREPLY VALUES(
DRNOSEQ.NEXTVAL, 14, 22, 1, 1, 1, '두 번째 글 두 번째 댓글의 답글', SYSDATE
)

