--굿즈
DROP TABLE GOODS;
DROP SEQUENCE GNO;

CREATE SEQUENCE GNO NOCACHE;
CREATE TABLE GOODS (
	GNO	NUMBER PRIMARY KEY,
	GCTGY VARCHAR2(100) NOT NULL,
	GNAME VARCHAR2(1000) NOT NULL,
	GPRICE NUMBER NOT NULL,
	GSTOCK NUMBER NOT NULL,
	GCOUNT NUMBER NOT NULL,
	GDATE DATE NOT NULL
	

);




SELECT*FROM GOODS;

INSERT INTO GOODS
VALUES (GNO.NEXTVAL, '과자', '고구마', 3000, '5', '2', SYSDATE);

INSERT INTO GOODS
VALUES (GNO.NEXTVAL, '수건', '수건', 3000, '100', '2', SYSDATE);

INSERT INTO GOODS
VALUES (GNO.NEXTVAL, '수건2', '수건2', 3000, '100', '2', SYSDATE);
INSERT INTO GOODS
VALUES (GNO.NEXTVAL, '수건3', '수건3', 3000, '100', '2', SYSDATE);
INSERT INTO GOODS
VALUES (GNO.NEXTVAL, '수건4', '수건4', 3000, '100', '2', SYSDATE);

SELECT * FROM GOODS;

commit

--굿즈 주문
DROP SEQUENCE GORNO;
DROP TABLE GOODSORDERS;

CREATE SEQUENCE GORNO NOCACHE;
CREATE TABLE GOODSORDERS (
	GORNO NUMBER PRIMARY KEY,
	GORSTATUS NUMBER NOT NULL,
	GORTOTALP NUMBER NOT NULL,
	MNO NUMBER NOT NULL,
	
	foreign key(MNO) references MEMBER(MNO)
);


SELECT*FROM GOODSORDERS;


--굿즈 주문 상세
DROP SEQUENCE GORDETAILNO;
DROP TABLE GOODSORDERDETAIL;

CREATE SEQUENCE GORDETAILNO NOCACHE;
CREATE TABLE GOODSORDERDETAIL(
	GORDETAILNO NUMBER PRIMARY KEY,
	GNO NUMBER NOT NULL,	
	GORNO NUMBER NOT NULL,
	MNO NUMBER NOT NULL,
	GQUT NUMBER NOT NULL,
	GORPRICE NUMBER NOT NULL,
	
	foreign key(GNO) references GOODS(GNO),
	foreign key(GORNO) references GOODSORDERS(GORNO),
	foreign key(MNO) references MEMBER(MNO)

);

SELECT*FROM GOODSORDERDETAIL;

COMMIT


INSERT INTO GOODS VALUES(GNO.NEXTVAL, '티셔츠', '티셔츠',28000, 20, 2, SYSDATE);



