drop table MEMBER;
DROP SEQUENCE MNO;

CREATE SEQUENCE MNO NOCACHE;

CREATE TABLE MEMBER (

    MNO NUMBER PRIMARY KEY,
    MROLE VARCHAR2(100) NOT NULL,
    MJOINYN VARCHAR2(2) NOT NULL,
    MID VARCHAR2(1000) NOT NULL,
    MPW VARCHAR2(1000) NOT NULL,
    MADDR1 VARCHAR2(1000) NOT NULL,
    MADDR2 VARCHAR2(1000) NOT NULL,
    MADDR3 VARCHAR2(1000) NOT NULL,
    MNAME VARCHAR2(1000) NOT NULL,
    MNICK VARCHAR2(1000) NOT NULL,
    MPHONE VARCHAR2(1000) NOT NULL,
    
    CONSTRAINT MJOINYN_CHK CHECK(MJOINYN IN('Y','N'))

);


DROP TABLE SMEMBER;

CREATE TABLE SMEMBER(

    SNO NUMBER,
    SBISNUM VARCHAR2(1000) NOT NULL,
    SSELLNUM VARCHAR2(1000) NOT NULL,
    
    foreign key(SNO) references MEMBER(MNO)

);

INSERT INTO MEMBER VALUES(
MNO.NEXTVAL,1,'Y','admin','1234','1234','서울시','아파트','관리자','관리자','01088349078'
);

COMMIT

SELECT * FROM MEMBER;
